# Generated by Django 2.2.14 on 2020-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('S', 'Sports'), ('H', 'Health'), ('B', 'Books'), ('C', 'Clothing'), ('SM', 'Smartphones'), ('A', 'Accessories'), ('K', 'Kids'), ('E', 'Electronics')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('Buy_url', models.TextField(default='#')),
            ],
        ),
    ]
