# Generated by Django 2.2.14 on 2020-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='blank', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='blank', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='blank', upload_to=''),
        ),
    ]
