# Generated by Django 3.0.2 on 2020-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200722_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sports'), ('H', 'Health & Beauty'), ('B', 'Books'), ('C', 'Clothing'), ('PH', 'Phones & Tablets'), ('A', 'Accessories'), ('K', 'Kids & Babi'), ('L', 'Laptops & PCs')], max_length=2),
        ),
    ]
